SysReservacionEventosESFE.UI.AppWebAspNetCore/Controllers/RolAccesosController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
/********************************/
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using System.Security.Claims;
using SysReservacionEventosESFE.EntidadesDeNegocio;
using SysReservacionEventosESFE.LogicaDeNegocio;
using SysReservacionEventosESFE.UI.AppWebAspNetCore.Models;
using SysReservacionEventosESFE.AccesoADatos;


namespace SysComercialMartinez.UI.AppWebAspNetCore.Controllers
{
    [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme)]

    public class RolAccesosController : Controller
    {

        RolAccesosBL RolAccesosBL = new RolAccesosBL();
        RolBL RolBL = new RolBL();
        AccesosBL AccesosBL = new AccesosBL();
        public static int idRol;

        // GET: ProductoController
        [AuthorizeUser(IdAcceso: 7)]
        public async Task<IActionResult> Index(RolAccesos pRolAccesos = null)
        {
            if (pRolAccesos == null)
                pRolAccesos = new RolAccesos();
            if (pRolAccesos.Top_Aux == 0)
                pRolAccesos.Top_Aux = 10;
            else if (pRolAccesos.Top_Aux == -1)
                pRolAccesos.Top_Aux = 0;
            var taskBuscar = RolAccesosBL.BuscarIncluirAccesoYRolAsync(pRolAccesos);
           
            var RolAccesoss = await taskBuscar;
    
            List<Rol> rol = await RolBL.ObtenerTodosAsync();
            List<Accesos> acc = await AccesosBL.ObtenerTodosAsync();
            ViewBag.Rol =  rol;
            ViewBag.Accesos = acc;
            ViewBag.Top = pRolAccesos.Top_Aux;
            return View(RolAccesoss);
        }



        // GET: RolAccesosController/Create
        [AuthorizeUser(IdAcceso: 7)]

        public async Task<IActionResult> Create()
        {
            ViewBag.Rol = await RolBL.ObtenerTodosAsync();
            ViewBag.Accesos = await AccesosBL.ObtenerTodosAsync();
            ViewBag.Error = "";
            return View();
        }

        // POST: RolAccesosController/Create
        [AuthorizeUser(IdAcceso: 7)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(RolAccesos pRolAccesos, string Rol, List<int> Acceso )
        {
            try
            {
                Rol objRol = new Rol();
                objRol.Nombre = Rol;
                await RolBL.CrearAsync(objRol);

                foreach (var acc in Acceso )
                {
                    RolAccesos nuevoRolAcceso = new RolAccesos();
                    nuevoRolAcceso.IdRol = objRol.Id;
                    nuevoRolAcceso.IdAcceso = acc;
                    await RolAccesosBL.CrearAsync(nuevoRolAcceso);
                }


                return RedirectToAction(nameof(Reportes));
            }
            catch (Exception ex)
            {
                ViewBag.Rol = await RolBL.ObtenerTodosAsync();
                ViewBag.Accesos = await AccesosBL.ObtenerTodosAsync();
                ViewBag.Error = ex.Message;
                return View(pRolAccesos);
            }
        }

        [AuthorizeUser(IdAcceso: 7)]
        public async Task<IActionResult> Edit(int IdRol)
        {
            var Rol = await RolBL.ObtenerPorIdAsync(new Rol { Id = IdRol });
            ViewBag.Accesos = await AccesosBL.ObtenerTodosAsync();
            ViewBag.RolId = IdRol;
            ViewBag.RolNombre = Rol != null ? Rol.Nombre : ""; // Pasar solo el nombre del rol a ViewBag
            ViewBag.Error = "";
            return View();
        }

        [AuthorizeUser(IdAcceso: 7)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(RolAccesos pRolAccesos, int IdRol, List<int> Acceso)
        {
            try
            {
             

                foreach (var acc in Acceso)
                {
                    RolAccesos nuevoRolAcceso = new RolAccesos();
                    nuevoRolAcceso.IdRol = IdRol;
                    nuevoRolAcceso.IdAcceso = acc;
                    await RolAccesosBL.CrearAsync(nuevoRolAcceso);
                }


                return RedirectToAction(nameof(Reportes));
            }
            catch (Exception ex)
            {
                ViewBag.Rol = await RolBL.ObtenerTodosAsync();
                ViewBag.Accesos = await AccesosBL.ObtenerTodosAsync();
                ViewBag.Error = ex.Message;
                return View(pRolAccesos);
            }
        }

        [AuthorizeUser(IdAcceso: 7)]
        // GET: RolAccesosController/Delete/5
        public async Task<IActionResult> Delete(RolAccesos pRolAccesos)
        {
            var RolAccesos = await RolAccesosBL.ObtenerPorIdAsync(pRolAccesos);
            RolAccesos.Rol = await RolBL.ObtenerPorIdAsync(new Rol { Id = RolAccesos.IdRol });
            RolAccesos.Accesos = await AccesosBL.ObtenerPorIdAsync(new Accesos { IdAcceso = RolAccesos.IdAcceso });
            ViewBag.Error = "";
            return View(RolAccesos);
        }

        // POST: RolAccesosController/Delete/5
        [AuthorizeUser(IdAcceso: 7)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int IdRolAccesos, RolAccesos pRolAccesos)
        {
            try
            {
                int result = await RolAccesosBL.EliminarAsync(pRolAccesos);
                return RedirectToAction(nameof(Reportes));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                var RolAccesos = await RolAccesosBL.ObtenerPorIdAsync(pRolAccesos);
                if (RolAccesos == null)
                    RolAccesos = new RolAccesos();
                if (RolAccesos.IdRolAcceso > 0)
                    RolAccesos.Rol = await RolBL.ObtenerPorIdAsync(new Rol { Id = RolAccesos.IdRol });
                if (RolAccesos.IdRolAcceso > 0)
                    RolAccesos.Accesos = await AccesosBL.ObtenerPorIdAsync(new Accesos { IdAcceso = RolAccesos.IdAcceso });
                return View(RolAccesos);
            }
        }

        [AuthorizeUser(IdAcceso: 7)]
        public async Task<IActionResult> Reportes(RolAccesos pRolAccesos, int IdRol)
        {
            List<Rol> rol = await RolBL.ObtenerTodosAsync();
            List<RolAccesos> rolAccesos = await RolAccesosBL.ObtenerTodosAsync();

            if (IdRol != 0)
            {
                ViewBag.Rol = rol.Where(r => r.Id == IdRol).ToList();
            }
            else
            {
                ViewBag.Rol = rol;

            }

            ViewBag.RolAcceso = rolAccesos;

            return View();
        }
    }
}

SysReservacionEventosESFE.UI.AppWebAspNetCore/Controllers/RolController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication;
/********************************/
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication.Cookies;
using SysReservacionEventosESFE.EntidadesDeNegocio;
using SysReservacionEventosESFE.LogicaDeNegocio;
using SysReservacionEventosESFE.UI.AppWebAspNetCore.Models;


namespace SysReservacionEventosESFE.UI.AppWebAspNetCore.Controllers
{
    [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme)]
    public class RolController : Controller
    {

        RolBL rolBL = new RolBL();
        // GET: RolController
        [AuthorizeUser(IdAcceso: 2)]
        public async Task<IActionResult> Index(Rol pRol = null)
        {
            if (pRol == null)
                pRol = new Rol();
            if (pRol.Top_Aux == 0)
                pRol.Top_Aux = 10;
            else if (pRol.Top_Aux == -1)
                pRol.Top_Aux = 0;
            var roles = await rolBL.BuscarAsync(pRol);
            ViewBag.Top = pRol.Top_Aux;
            return View(roles);
        }

        [AuthorizeUser(IdAcceso: 2)]
        // GET: RolController/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var rol = await rolBL.ObtenerPorIdAsync(new Rol { Id = id });
            return View(rol);
        }

        [AuthorizeUser(IdAcceso: 2)]
        // GET: RolController/Create
        public IActionResult Create()
        {
            ViewBag.Error = "";
            return View();
        }

        [AuthorizeUser(IdAcceso: 2)]
        // POST: RolController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Rol pRol)
        {
            try
            {
                int result = await rolBL.CrearAsync(pRol);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(pRol);
            }
        }

        [AuthorizeUser(IdAcceso: 2)]
        // GET: RolController/Edit/5
        public async Task<IActionResult> Edit(Rol pRol)
        {
            var rol = await rolBL.ObtenerPorIdAsync(pRol);
            ViewBag.Error = "";
            return View(rol);
        }

        [AuthorizeUser(IdAcceso: 2)]
        // POST: RolController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Rol pRol)
        {
            try
            {
                int result = await rolBL.ModificarAsync(pRol);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(pRol);
            }
        }

        [AuthorizeUser(IdAcceso: 2)]
        // GET: RolController/Delete/5
        public async Task<IActionResult> Delete(Rol pRol)
        {
            ViewBag.Error = "";
            var rol = await rolBL.ObtenerPorIdAsync(pRol);
            return View(rol);
        }

        [AuthorizeUser(IdAcceso: 2)]
        // POST: RolController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id, Rol pRol)
        {
            try
            {
                int result = await rolBL.EliminarAsync(pRol);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(pRol);
            }
        }
    }
}

SysReservacionEventosESFE.UI.AppWebAspNetCore/Views/Rol/Create.cshtml
@model SysReservacionEventosESFE.EntidadesDeNegocio.Rol
@{
    Layout = null;
}
@{
    ViewData["Title"] = "Create";
}

<h1>Agregar rol</h1>
<hr />


<form asp-action="Create">

    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
        </div>
    </div>
    @*BOTONES GUARDAR Y CANCELAR*@

    <div class="form-group" style="margin-top: 10px;">
        <button type="submit" class="btn btn-success" style="margin-right: 10px;">
            <i class="fas fa-save"></i> Guardar
        </button>

        <button type="button" class="btn btn-danger" onclick="window.location.href='@Url.Action("Index")'" style="margin-left: 10px;">
            <i class="fas fa-times"></i> Cancelar
        </button>
    </div>

    <span class="text-danger">@ViewBag.Error</span>

</form>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

SysReservacionEventosESFE.UI.AppWebAspNetCore/Views/Rol/Delete.cshtml
@model SysReservacionEventosESFE.EntidadesDeNegocio.Rol

@{
    ViewData["Title"] = "Delete";
}
<h1>Eliminar rol</h1>

<h3>¿ Esta seguro que desea eliminar ?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
    </dl>

    @* FUNCTION ELIMINAR ROL*@
    @using (Html.BeginForm("Delete", "Rol", new { id = Model.Id }, FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <button type="submit" class="btn btn-danger" onclick="return confirm('¿Está seguro de eliminar?');" style="margin-left: 10px;">
            <i class="fas fa-trash"></i> Eliminar
        </button>

        <button type="button" class="btn btn-secondary" onclick="window.location.href='@Url.Action("Index")'" style="margin-left: 10px;">
            <i class="fas fa-times"></i> Cancelar
        </button>
        <span class="text-danger">@ViewBag.Error</span>
    }

</div>

SysReservacionEventosESFE.UI.AppWebAspNetCore/Views/Rol/Details.cshtml
@model SysReservacionEventosESFE.EntidadesDeNegocio.Rol

@{
    ViewData["Title"] = "Details";
}

<h1>Detalles de rol</h1>
<hr />
<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
    </dl>
</div>

@*BOTONES DE DETALLES DE ROL*@

<td class="botonestabla">
    <button type="button" class="btn btn-success" style="background-color: #264DA0; color: white; margin-right: 10px;" onclick="window.location.href='@Url.Action("Edit", new { id = Model.Id })'">
        <i class="fas fa-pencil-alt"></i> Ir a Modificar
    </button>
</td>

<td class="botonestabla">
    <button type="button" class="btn btn-danger" onclick="window.location.href='@Url.Action("Index")'" style="margin-left: 10px;">
        <i class="fas fa-times"></i> Cancelar
    </button>
</td>

SysReservacionEventosESFE.UI.AppWebAspNetCore/Views/Rol/Edit.cshtml
@model SysReservacionEventosESFE.EntidadesDeNegocio.Rol

@{
    ViewData["Title"] = "Edit";
}
<h1>Modificar rol</h1>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" class="form-control" />
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>

            @*BOTONES DE EDIT DE ROL*@

            <div class="form-group" style="margin-top: 10px;">
                <button type="submit" class="btn btn-success" style="margin-right: 10px;">
                    <i class="fas fa-save"></i> Guardar
                </button>

                <button type="button" class="btn btn-danger" onclick="window.location.href='@Url.Action("Index")'" style="margin-left: 10px;">
                    <i class="fas fa-times"></i> Cancelar
                </button>
            </div>
            <span class="text-danger">@ViewBag.Error</span>

        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script>
        $(function () {
            $("form input[name]").trigger("blur");
        });
    </script>
} 

SysReservacionEventosESFE.UI.AppWebAspNetCore/Views/Rol/Index.cshtml
@model IEnumerable<SysReservacionEventosESFE.EntidadesDeNegocio.Rol>


@{
    ViewData["Title"] = "Index";
    int numPage = 1;
    int numRegistros = 0;
    int numRegistrosPorPage = 10;
    int[] tops = { 10, 20, 50, 100, 500, 1000, 10000, -1 };
    int topActual = Convert.ToInt32(ViewBag.Top);
}
<h1>Buscar rol</h1>
<div class="row">
    <div class="col-md-12">
        <form asp-action="Index">
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label class="control-label">Nombre</label>
                        <input type="text" class="form-control" name="nombre" />
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        <label class="control-label">Top</label>
                        <select name="top_aux" class="form-control">
                            @foreach (var item in tops)
                            {
                                string strItem = item != -1 ? item.ToString() : "Todos";
                                if (item != topActual)
                                {
                                    <option value="@item">@strItem</option>
                                }
                                else
                                {
                                    <option selected value="@item">@strItem</option>
                                }
                            }
                        </select>
                    </div>
                </div>
            </div>

            @*BOTONES DE CREAR Y BUSCAR DE ROL*@


            <div class="form-group" style="margin-top: 10px;">
                <button type="submit" class="btn btn-primary" style="background-color: #0074D9; color: white;">
                    <i class="fas fa-search"></i> Buscar
                </button>

                <button type="button" class="btn btn-success" onclick="window.location.href='@Url.Action("Create", "RolAccesos")'">
                    <i class="fas fa-plus"></i> Agregar
                </button>

            </div>

            <span class="text-danger">@ViewBag.Error</span>

        </form>
    </div>
</div>



<table class="table table-responsive paginationjs">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th colspan="3">Acciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr data-page="@numPage">
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>

                @*BOTONES CRUD EDITAR - LEER - ELIMINAR ROL*@


                
                <td class="botonestabla">
                    <button type="button" class="btn btn-primary" style="background-color: #264DA0; color: white" onclick="window.location.href='@Url.Action("Edit", new { id = item.Id })'">
                        <i class="fas fa-pencil-alt"></i> Modificar
                    </button>
                </td>


                <td class="botonestabla">
                    <button type="button" class="btn btn-info" onclick="window.location.href='@Url.Action("Details", new { id = item.Id })'">
                        <i class="fas fa-eye"></i> Detalles
                    </button>
                </td>
                <td class="botonestabla">
                    <button type="button" class="btn btn-danger" onclick="window.location.href='@Url.Action("Delete", new { id = item.Id })'">
                        <i class="fas fa-trash"></i> Eliminar
                    </button>
                </td>

            </tr>
            numRegistros++;
            if (numRegistros == numRegistrosPorPage)
            {
                numPage++;
                numRegistros = 0;
            }
        }
        @{
            if (numRegistros == 0)
            {
                numPage--;
            }
        }
    </tbody>
</table>
@if (numPage > 1)
{
    <div class="row" style="overflow:auto">
        <div class="col-md-12">
            <ul class="pagination paginationjs" data-numpage="@numPage" data-pageactive="1">
                <li class="page-item" data-typepage="Previous"><a class="page-link" href="#">Previous</a></li>
                @for (var i = 1; i <= numPage; i++)
                {
                    <li class="page-item" data-page="@i" data-typepage="Item"><a class="page-link" href="#">@i</a></li>
                }
                <li class="page-item" data-typepage="Next"><a class="page-link" href="#">Next</a></li>
            </ul>
        </div>
    </div>
}