SysReservacionEventosESFE.UI.AppWebAspNetCore/Controllers/EspaciosAController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SysReservacionEventosESFE.EntidadesDeNegocio;
using SysReservacionEventosESFE.LogicaDeNegocio;
using System.Data;
using SysReservacionEventosESFE.UI.AppWebAspNetCore.Models;


namespace SysReservacionEventosESFE.UI.AppWebAspNetCore.Controllers
{
    [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme)]
    public class EspaciosAController : Controller
    {
        EspaciosABL EspaciosABL = new EspaciosABL();
        // GET: EspaciosAController
        [AuthorizeUser(IdAcceso: 6)]

        public async Task<IActionResult> Index(EspaciosA pEspaciosA = null)
        {
            if (pEspaciosA == null)
                pEspaciosA = new EspaciosA();
            if (pEspaciosA.Top_Aux == 0)
                pEspaciosA.Top_Aux = 10;
            else if (pEspaciosA.Top_Aux == -1)
                pEspaciosA.Top_Aux = 0;
            var EspaciosAes = await EspaciosABL.BuscarAsync(pEspaciosA);
            ViewBag.Top = pEspaciosA.Top_Aux;
            return View(EspaciosAes);
        }

        [AuthorizeUser(IdAcceso: 6)]
        // GET: EspaciosAContEspaciosAler/Details/5
        public async Task<IActionResult> Details(int IdEspaciosA)
        {
            var EspaciosA = await EspaciosABL.ObtenerPorIdAsync(new EspaciosA { IdEspaciosA = IdEspaciosA });
            return View(EspaciosA);
        }


        [AuthorizeUser(IdAcceso: 6)]
        // GET: EspaciosAContEspaciosAler/Create
        public IActionResult Create()
        {
            ViewBag.Error = "";
            return View();
        }

        // POST: EspaciosAContEspaciosAler/Create
        [AuthorizeUser(IdAcceso: 6)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(EspaciosA pEspaciosA)
        {
            try
            {
                int result = await EspaciosABL.CrearAsync(pEspaciosA);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(pEspaciosA);
            }
        }

        // GET: EspaciosAContEspaciosAler/Edit/5
        [AuthorizeUser(IdAcceso: 6)]
        public async Task<IActionResult> Edit(EspaciosA pEspaciosA)
        {
            var EspaciosA = await EspaciosABL.ObtenerPorIdAsync(pEspaciosA);
            ViewBag.Error = "";
            return View(EspaciosA);
        }

        // POST: EspaciosAContEspaciosAler/Edit/5
        [AuthorizeUser(IdAcceso: 6)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int IdAsinacion, EspaciosA pEspaciosA)
        {
            try
            {
                int result = await EspaciosABL.ModificarAsync(pEspaciosA);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(pEspaciosA);
            }
        }

        // GET: EspaciosAContEspaciosAler/Delete/5
        [AuthorizeUser(IdAcceso: 6)]
        public async Task<IActionResult> Delete(EspaciosA pEspaciosA)
        {
            ViewBag.Error = "";
            var EspaciosA = await EspaciosABL.ObtenerPorIdAsync(pEspaciosA);
            return View(EspaciosA);
        }

        // POST: EspaciosAContEspaciosAler/Delete/5
        [AuthorizeUser(IdAcceso: 6)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int IdEspaciosA, EspaciosA pEspaciosA)
        {
            try
            {
                int result = await EspaciosABL.EliminarAsync(pEspaciosA);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(pEspaciosA);
            }
        }
    }
}

SysReservacionEventosESFE.UI.AppWebAspNetCore/Views/EspaciosA/Create.cshtml
@model SysReservacionEventosESFE.EntidadesDeNegocio.EspaciosA

@{
    ViewData["Title"] = "Create";
}

<h1>Agregar espacio</h1>


<hr />

<form asp-action="Create">

    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <select asp-for="Status" class="form-control">
                    <option value="">SELECCIONAR</option>
                    <option selected value="1">DISPONIBLE</option>
                    <option value="2">OCUPADO</option>
                </select>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
        </div>
    </div>

    @*BOTONES GUARDAR Y CANCELAR*@

    <div class="form-group" style="margin-top: 10px;">
        <button type="submit" class="btn btn-success" style="margin-right: 10px;">
            <i class="fas fa-save"></i> Guardar
        </button>

        <button type="button" class="btn btn-danger" onclick="window.location.href='@Url.Action("Index")'" style="margin-left: 10px;">
            <i class="fas fa-times"></i> Cancelar
        </button>
    </div>

    <span class="text-danger">@ViewBag.Error</span>

</form>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

SysReservacionEventosESFE.UI.AppWebAspNetCore/Views/EspaciosA/Delete.cshtml
@model SysReservacionEventosESFE.EntidadesDeNegocio.EspaciosA

@{
    ViewData["Title"] = "Delete";
}

<h1>Eliminar espacio</h1>

<h3>¿ Esta seguro que desea eliminar ?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        @if (Model.Status == 1)
        {
            <dd class="col-sm-10">
                DISPONIBLE
            </dd>
        }
        else if (Model.Status == 2)
        {
            <dd class="col-sm-10">
                OCUPADO
            </dd>
        }
        else
        {
            <dd class="col-sm-10"> </dd>
        }

    </dl>

    @* FUNCTION ELIMINAR ROL*@
    @using (Html.BeginForm("Delete", "EspaciosA", new { IdEspaciosA = Model.IdEspaciosA }, FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <button type="submit" class="btn btn-danger" onclick="return confirm('¿Está seguro de eliminar?');" style="margin-left: 10px;">
            <i class="fas fa-trash"></i> Eliminar
        </button>

        <button type="button" class="btn btn-secondary" onclick="window.location.href='@Url.Action("Index")'" style="margin-left: 10px;">
            <i class="fas fa-times"></i> Cancelar
        </button>
        <span class="text-danger">@ViewBag.Error</span>
    }

</div>

SysReservacionEventosESFE.UI.AppWebAspNetCore/Views/EspaciosA/Details.cshtml
@model SysReservacionEventosESFE.EntidadesDeNegocio.EspaciosA

@{
    ViewData["Title"] = "Details";
}

<h1>Detalles de espacio</h1>

<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class="col-sm-2">
            Estado
        </dt>
        @if (Model.Status == 1)
        {
            <dd class="col-sm-10">
                DISPONIBLE
            </dd>
        }
        else if (Model.Status == 2)
        {
            <dd class="col-sm-10">
                OCUPADO
            </dd>
        }
        else
        {
            <dd class="col-sm-10"> </dd>
        }
    </dl>
</div>
<div>
    <td class="botonestabla">
        <button type="button" class="btn btn-success" style="background-color: #264DA0; color: white; margin-right: 10px;" onclick="window.location.href='@Url.Action("Edit", new { IdEspaciosA = Model.IdEspaciosA })'">
            <i class="fas fa-pencil-alt"></i> Ir a Modificar
        </button>
    </td>

    <td class="botonestabla">
        <button type="button" class="btn btn-danger" onclick="window.location.href='@Url.Action("Index")'" style="margin-left: 10px;">
            <i class="fas fa-times"></i> Cancelar
        </button>
    </td>
</div>

SysReservacionEventosESFE.UI.AppWebAspNetCore/Views/EspaciosA/Edit.cshtml
@model SysReservacionEventosESFE.EntidadesDeNegocio.EspaciosA

@{
    ViewData["Title"] = "Edit";
}

<h1>Modificar espacio</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdEspaciosA" class="form-control" />
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label">Estado</label>
                    <select asp-for="Status" class="form-control">
                        <option selected value="">SELECCIONAR</option>
                        @if (Model.Status == 1)
                        {
                            <option selected value="1">DISPONNIBLE</option>
                        }
                        else
                        {
                            <option value="1">ACTIVO</option>
                        }
                        @if (Model.Status == 2)
                        {
                            <option selected value="2">OCUPADO</option>
                        }
                        else
                        {
                            <option value="2">INACTIVO</option>
                        }

                    </select>
                    <span class="text-danger">Estatus</span>
                </div>
            </div>

            @*BOTONES DE EDIT DE ROL*@

            <div class="form-group" style="margin-top: 10px;">
                <button type="submit" class="btn btn-success" style="margin-right: 10px;">
                    <i class="fas fa-save"></i> Guardar
                </button>

                <button type="button" class="btn btn-danger" onclick="window.location.href='@Url.Action("Index")'" style="margin-left: 10px;">
                    <i class="fas fa-times"></i> Cancelar
                </button>
            </div>
            <span class="text-danger">@ViewBag.Error</span>

        </form>
    </div>
</div>



@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

SysReservacionEventosESFE.UI.AppWebAspNetCore/Views/EspaciosA/Index.cshtml
@model IEnumerable<SysReservacionEventosESFE.EntidadesDeNegocio.EspaciosA>


@{
    ViewData["Title"] = "Index";
    int numPage = 1;
    int numRegistros = 0;
    int numRegistrosPorPage = 10;
    int[] tops = { 10, 20, 50, 100, 500, 1000, 10000, -1 };
    int topActual = Convert.ToInt32(ViewBag.Top);
}
<h1>Buscar espacio</h1>
<div class="row">
    <div class="col-md-12">
        <form asp-action="Index">
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label class="control-label">Nombre</label>
                        <input type="text" class="form-control" name="nombre" />
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        <label class="control-label">Top</label>
                        <select name="top_aux" class="form-control">
                            @foreach (var item in tops)
                            {
                                string strItem = item != -1 ? item.ToString() : "Todos";
                                if (item != topActual)
                                {
                                    <option value="@item">@strItem</option>
                                }
                                else
                                {
                                    <option selected value="@item">@strItem</option>
                                }
                            }
                        </select>
                    </div>
                </div>
            </div>

            @*BOTONES DE CREAR Y BUSCAR DE ROL*@


            <div class="form-group" style="margin-top: 10px;">
                <button type="submit" class="btn btn-primary" style="background-color: #0074D9; color: white;">
                    <i class="fas fa-search"></i> Buscar
                </button>


                <button type="button" class="btn btn-success" onclick="window.location.href='@Url.Action("Create")'">
                    <i class="fas fa-plus"></i> Agregar
                </button>
            </div>

            <span class="text-danger">@ViewBag.Error</span>

        </form>
    </div>
</div>



<table class="table table-responsive paginationjs">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                Estado
            </th>
            <th colspan="3">Acciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr data-page="@numPage">
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                @if (item.Status == 1)
                {
                    <td>DISPONIBLE</td>
                }
                else if (item.Status == 2)
                {
                    <td>OCUPADO</td>
                }
                else
                {
                    <td></td>
                }

                @*BOTONES CRUD EDITAR - LEER - ELIMINAR ROL*@



                <td class="botonestabla">
                    <button type="button" class="btn btn-primary" style="background-color: #264DA0; color: white" onclick="window.location.href='@Url.Action("Edit", new { IdEspaciosA = item.IdEspaciosA })'">
                        <i class="fas fa-pencil-alt"></i> Modificar
                    </button>
                </td>


                <td class="botonestabla">
                    <button type="button" class="btn btn-info" onclick="window.location.href='@Url.Action("Details", new { IdEspaciosA = item.IdEspaciosA })'">
                        <i class="fas fa-eye"></i> Detalles
                    </button>
                </td>
                <td class="botonestabla">
                    <button type="button" class="btn btn-danger" onclick="window.location.href='@Url.Action("Delete", new { IdEspaciosA = item.IdEspaciosA })'">
                        <i class="fas fa-trash"></i> Eliminar
                    </button>
                </td>

            </tr>
            numRegistros++;
            if (numRegistros == numRegistrosPorPage)
            {
                numPage++;
                numRegistros = 0;
            }
        }
        @{
            if (numRegistros == 0)
            {
                numPage--;
            }
        }
    </tbody>
</table>
@if (numPage > 1)
{
    <div class="row" style="overflow:auto">
        <div class="col-md-12">
            <ul class="pagination paginationjs" data-numpage="@numPage" data-pageactive="1">
                <li class="page-item" data-typepage="Previous"><a class="page-link" href="#">Previous</a></li>
                @for (var i = 1; i <= numPage; i++)
                {
                    <li class="page-item" data-page="@i" data-typepage="Item"><a class="page-link" href="#">@i</a></li>
                }
                <li class="page-item" data-typepage="Next"><a class="page-link" href="#">Next</a></li>
            </ul>
        </div>
    </div>
}