SysReservacionEventosESFE.UI.AppWebAspNetCore/Controllers/EventoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

/********************************/
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication.Cookies;
using SysReservacionEventosESFE.EntidadesDeNegocio;
using SysReservacionEventosESFE.LogicaDeNegocio;
using SysReservacionEventosESFE.UI.AppWebAspNetCore.Models;



namespace SysReservacionEventosESFE.UI.AppWebAspNetCore.Controllers
{
    [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme)]
    public class EventoController : Controller
    {
        EventoBL EventoBL = new EventoBL();
        CarreraBL CarreraBL = new CarreraBL();
        EspaciosABL EspaciosABL = new EspaciosABL();
        UsuarioBL UsuarioBL = new UsuarioBL();
        InstitucionBL InstitucionBL = new InstitucionBL();


        // GET: EventoController
        [AuthorizeUser(IdAcceso: 3)]
        public async Task<IActionResult> Index(DateTime fInicio, DateTime fFinal, Evento pEvento = null)
        {
            if (pEvento == null)
                pEvento = new Evento();
            if (pEvento.Top_Aux == 0)
                pEvento.Top_Aux = 10;
            else if (pEvento.Top_Aux == -1)
                pEvento.Top_Aux = 0;
            var taskBuscar = EventoBL.BuscarIncluirUsuarioCarreraInstitucionEspaciosAAsync(pEvento);
            var taskObtenerTodos = CarreraBL.ObtenerTodosAsync();
            var taskObtenerTodosE = EspaciosABL.ObtenerTodosAsync();
            var taskObtenerTodosU = UsuarioBL.ObtenerTodosAsync();
            var taskObtenerTodosI = InstitucionBL.ObtenerTodosAsync();
            var Eventos = await taskBuscar;
            ViewBag.Carrera = await taskObtenerTodos;
            ViewBag.Espacios = await taskObtenerTodosE;
            ViewBag.Usuario = await taskObtenerTodosU;
            ViewBag.Institucion = await taskObtenerTodosI;
            ViewBag.Top = pEvento.Top_Aux;
            if (fInicio.Year != 1 && fFinal.Year != 1)
            {
                ViewBag.Evento = Eventos.Where(r => r.FechaEvento.Date >= fInicio.Date && r.FechaEvento.Date <= fFinal.Date).ToList();
            }
            else
            {
                ViewBag.Evento = Eventos;
            }
            return View(Eventos);
        }

        [AuthorizeUser(IdAcceso: 3)]
        // GET: ProductoController/Details/5
        public async Task<IActionResult> Details(int IdEvento)
        {
            var Evento = await EventoBL.ObtenerPorIdAsync(new Evento { IdEvento = IdEvento });
            Evento.Carrera = await CarreraBL.ObtenerPorIdAsync(new Carrera { IdCarrera = Evento.IdCarrera });
            Evento.EspaciosA = await EspaciosABL.ObtenerPorIdAsync(new EspaciosA { IdEspaciosA = Evento.IdEspaciosA });
            Evento.Usuario = await UsuarioBL.ObtenerPorIdAsync(new Usuario { Id = Evento.IdUsuario });
            Evento.Institucion = await InstitucionBL.ObtenerPorIdAsync(new Institucion { IdInstitucion = Evento.IdInstitucion });
            return View(Evento);
        }

        // GET: ProductoController/Create

        [AuthorizeUser(IdAcceso: 3)]
        public async Task<IActionResult> Create()
        {
            ViewBag.Carrera = await CarreraBL.ObtenerTodosAsync();
            ViewBag.Espacios = await EspaciosABL.ObtenerTodosAsync();
            ViewBag.Usuario = await UsuarioBL.ObtenerTodosAsync();
            ViewBag.Institucion = await InstitucionBL.ObtenerTodosAsync();

            ViewBag.Error = "";
            return View();
        }

        [AuthorizeUser(IdAcceso: 3)]
        // POST: ProductoController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Evento pEvento)
        {
            try
            {

                int result = await EventoBL.CrearAsync(pEvento);
                return RedirectToAction(nameof(Index));

            }
            catch (Exception ex)
            {
                ViewBag.Carrera = await CarreraBL.ObtenerTodosAsync();
                ViewBag.Espacios = await EspaciosABL.ObtenerTodosAsync();
                ViewBag.Usuario = await UsuarioBL.ObtenerTodosAsync();
                ViewBag.Institucion = await InstitucionBL.ObtenerTodosAsync();
                ViewBag.Error = ex.Message;
                return View(pEvento);
            }
        }

        [AuthorizeUser(IdAcceso: 3)]
        // GET: ProductoController/Edit/5
        public async Task<IActionResult> Edit(Evento pEvento)
        {
            var taskObtenerPorId = EventoBL.ObtenerPorIdAsync(pEvento);
            var taskObtenerTodos = CarreraBL.ObtenerTodosAsync();
            var taskObtenerTodosE = EspaciosABL.ObtenerTodosAsync();
            var taskObtenerTodosU = UsuarioBL.ObtenerTodosAsync();
            var taskObtenerTodosI = InstitucionBL.ObtenerTodosAsync();
            var Evento = await taskObtenerPorId;
            ViewBag.Espacios = await taskObtenerTodosE;
            ViewBag.Usuario = await taskObtenerTodosU;
            ViewBag.Institucion = await taskObtenerTodosI;
            ViewBag.Carrera = await taskObtenerTodos;
            ViewBag.Error = "";
            return View(Evento);
        }

        [AuthorizeUser(IdAcceso: 3)]
        // POST: EventoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int IdEvento, Evento pEvento,int IdEspaciosA)
        {
            try
            {
                // Obtener todos los eventos existentes
                var todosEventos = await EventoBL.ObtenerTodosAsync();

                // Verificar si hay algún evento existente con superposición de horas en el mismo lugar y fecha
                foreach (var evento in todosEventos)
                {
                    if (evento.FechaEvento.Date == pEvento.FechaEvento.Date && // Compara solo la fecha sin la hora
                        evento.EspaciosA.IdEspaciosA == IdEspaciosA && // Compara el nombre del lugar
                        SeSuperponenHoras(pEvento.HoraInicio, pEvento.HoraFin, evento.HoraInicio, evento.HoraFin))
                    {
                        string mensaje = "Las horas seleccionadas se superponen con otro evento en el mismo lugar y fecha. Por favor, elige otras horas.";

                        ViewBag.Mensaje = mensaje;

                        // Devolver la vista con el mensaje de error
                        return RedirectToAction(nameof(YaReservado));



                    }
                }


                pEvento.IdUsuario = global.idu;

                int result = await EventoBL.ModificarAsync(pEvento);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Carrera = await CarreraBL.ObtenerTodosAsync();
                ViewBag.Espacios = await EspaciosABL.ObtenerTodosAsync();
                ViewBag.Usuario = await UsuarioBL.ObtenerTodosAsync();
                ViewBag.Institucion = await InstitucionBL.ObtenerTodosAsync();
                ViewBag.Error = ex.Message;
                return View(pEvento);
            }
        }

        [AuthorizeUser(IdAcceso: 3)]
        // GET: EventoController/Delete/5
        public async Task<IActionResult> Delete(Evento pEvento)
        {
            var Evento = await EventoBL.ObtenerPorIdAsync(pEvento);
            Evento.Carrera = await CarreraBL.ObtenerPorIdAsync(new Carrera { IdCarrera = Evento.IdCarrera });
            Evento.EspaciosA = await EspaciosABL.ObtenerPorIdAsync(new EspaciosA { IdEspaciosA = Evento.IdEspaciosA });
            Evento.Usuario = await UsuarioBL.ObtenerPorIdAsync(new Usuario { Id = Evento.IdUsuario });
            Evento.Institucion = await InstitucionBL.ObtenerPorIdAsync(new Institucion { IdInstitucion = Evento.IdInstitucion });
            ViewBag.Error = "";
            return View(Evento);
        }

        [AuthorizeUser(IdAcceso: 3)]
        // POST: ProductoController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int IdEvento, Evento pEvento)
        {
            try
            {
                int result = await EventoBL.EliminarAsync(pEvento);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                var Evento = await EventoBL.ObtenerPorIdAsync(pEvento);
                if (Evento == null)
                    Evento = new Evento();
                if (Evento.IdCarrera > 0)
                    Evento.Carrera = await CarreraBL.ObtenerPorIdAsync(new Carrera { IdCarrera = Evento.IdCarrera });
                if (Evento.IdCarrera > 0)
                    Evento.Carrera = await CarreraBL.ObtenerPorIdAsync(new Carrera { IdCarrera = Evento.IdCarrera });
                if (Evento.IdEspaciosA > 0)
                    Evento.EspaciosA = await EspaciosABL.ObtenerPorIdAsync(new EspaciosA { IdEspaciosA = Evento.IdEspaciosA });
                if (Evento.IdUsuario > 0)
                    Evento.Usuario = await UsuarioBL.ObtenerPorIdAsync(new Usuario { Id = Evento.IdUsuario });
                if (Evento.IdInstitucion > 0)
                    Evento.Institucion = await InstitucionBL.ObtenerPorIdAsync(new Institucion { IdInstitucion = Evento.IdInstitucion });
                return View(Evento);
            }
        }

        [AuthorizeUser(IdAcceso: 3)]
        public async Task<IActionResult> Reserva()
        {
            ViewBag.Carrera = await CarreraBL.ObtenerTodosAsync();
            ViewBag.Espacios = await EspaciosABL.ObtenerTodosAsync();
            ViewBag.Usuario = await UsuarioBL.ObtenerTodosAsync();
            ViewBag.Institucion = await InstitucionBL.ObtenerTodosAsync();

            ViewBag.Error = "";
            return View();
        }

SysReservacionEventosESFE.UI.AppWebAspNetCore/Controllers/RolController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication;
/********************************/
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication.Cookies;
using SysReservacionEventosESFE.EntidadesDeNegocio;
using SysReservacionEventosESFE.LogicaDeNegocio;
using SysReservacionEventosESFE.UI.AppWebAspNetCore.Models;


namespace SysReservacionEventosESFE.UI.AppWebAspNetCore.Controllers
{
    [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme)]
    public class RolController : Controller
    {

        RolBL rolBL = new RolBL();
        // GET: RolController
        [AuthorizeUser(IdAcceso: 2)]
        public async Task<IActionResult> Index(Rol pRol = null)
        {
            if (pRol == null)
                pRol = new Rol();
            if (pRol.Top_Aux == 0)
                pRol.Top_Aux = 10;
            else if (pRol.Top_Aux == -1)
                pRol.Top_Aux = 0;
            var roles = await rolBL.BuscarAsync(pRol);
            ViewBag.Top = pRol.Top_Aux;
            return View(roles);
        }

        [AuthorizeUser(IdAcceso: 2)]
        // GET: RolController/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var rol = await rolBL.ObtenerPorIdAsync(new Rol { Id = id });
            return View(rol);
        }

        [AuthorizeUser(IdAcceso: 2)]
        // GET: RolController/Create
        public IActionResult Create()
        {
            ViewBag.Error = "";
            return View();
        }

        [AuthorizeUser(IdAcceso: 2)]
        // POST: RolController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Rol pRol)
        {
            try
            {
                int result = await rolBL.CrearAsync(pRol);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(pRol);
            }
        }

        [AuthorizeUser(IdAcceso: 2)]
        // GET: RolController/Edit/5
        public async Task<IActionResult> Edit(Rol pRol)
        {
            var rol = await rolBL.ObtenerPorIdAsync(pRol);
            ViewBag.Error = "";
            return View(rol);
        }

        [AuthorizeUser(IdAcceso: 2)]
        // POST: RolController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Rol pRol)
        {
            try
            {
                int result = await rolBL.ModificarAsync(pRol);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(pRol);
            }
        }

        [AuthorizeUser(IdAcceso: 2)]
        // GET: RolController/Delete/5
        public async Task<IActionResult> Delete(Rol pRol)
        {
            ViewBag.Error = "";
            var rol = await rolBL.ObtenerPorIdAsync(pRol);
            return View(rol);
        }

        [AuthorizeUser(IdAcceso: 2)]
        // POST: RolController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id, Rol pRol)
        {
            try
            {
                int result = await rolBL.EliminarAsync(pRol);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(pRol);
            }
        }
    }
}

SysReservacionEventosESFE.UI.AppWebAspNetCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Reservas ESFE</title>
    <!--    https://fontawesome.com/   -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.19.0/font/bootstrap-icons.css" rel="stylesheet">
    <!-- Incluye jQuery desde el CDN de Google -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    @*Link para iconos*@
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha512-......" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/Home.css">
    <link rel="stylesheet" href="~/css/Menu.css">
    <link rel="stylesheet" href="~/css/Inicio.css">
    <link rel="stylesheet" href="~/css/VentaCompra.css">


</head>

<body>
    <header>
        <label class="labelMenu"><i class="fa fa-bars"></i></label>

    </header>
    <header>
        @{
            string? nombre = User.Identity.Name;
            int? Idu = global.idu;

        }


    </header>
    <div class="menu">
        
        <nav>
            <ul>
                <div class="logo-container">
                    <!-- Aquí puedes agregar el código o la imagen del logotipo de tu empresa -->
                    <!-- Por ejemplo, si es una imagen: -->
                    <center> <img src="~/IMG/esfe.png" alt="Logo de la empresa" class="logo-container"></center>
                </div>



                <li class="Nombre">
                    <a class="dashboard-nav-dropdown-item-nombre">Bienvenido @nombre </a>

                </li>


                
                
                    <li class="nav-item">
                        <a class="dashboard-nav-dropdown-item" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                    </li>
                    <li class="nav-item">
                        <a class="dashboard-nav-dropdown-item" asp-area="" asp-controller="Usuario" asp-action="Index">Usuario</a>
                    </li>
                    <li class="nav-item">
                        <a class="dashboard-nav-dropdown-item" asp-area="" asp-controller="Rol" asp-action="Index">Rol</a>
                    </li>
                <li class="nav-item">
                    <a class="dashboard-nav-dropdown-item" asp-area="" asp-controller="RolAccesos" asp-action="Reportes">Accesos</a>
                </li>
                    <li class="nav-item">
                        <a class="dashboard-nav-dropdown-item" asp-area="" asp-controller="Carrera" asp-action="Index">Carrera</a>
                    </li>
                    <li class="nav-item">
                        <a class="dashboard-nav-dropdown-item" asp-area="" asp-controller="Evento" asp-action="Index">Evento</a>
                    </li>
                     <li class="nav-item">
                        <a class="dashboard-nav-dropdown-item" asp-area="" asp-controller="Institucion" asp-action="Index">Institucion</a>
                    </li>
                    <li class="nav-item">
                        <a class="dashboard-nav-dropdown-item" asp-area="" asp-controller="EspaciosA" asp-action="Index">Espacios</a>
                    </li>
                       
                    <li class="nav-item">
                        <a class="dashboard-nav-dropdown-item" asp-area="" asp-controller="Usuario" asp-action="CambiarPassword">Cambiar password</a>
                    </li>
                    <li class="nav-item">
                        <a class="dashboard-nav-item" asp-area="" asp-controller="Usuario" asp-action="CerrarSesion">Cerrar sesión</a>
                    </li>
                
                
               
            </ul>


        </nav>
    </div>
    <div class="opacMenu"></div>

    <!--  Jquery  -->
    <div class='dashboard-content'>
        <div class='dashboard-app'>
            <div class='container'>
                <main role="main" class="pb-2">
                    @RenderBody()
                </main>
            </div>
        </div>
    </div>



    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/Inicio.js"></script>
    <script src="~/js/Venta.js"></script>
    <script src="~/js/Menu.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/JavaScriptHome.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

    <script>

        function printDiv() {
            var divToPrint = document.getElementById('divToPrint');
            var newWin = window.open('', 'Print-Window');
            newWin.document.open();
            newWin.document.write('<html><body onload="window.print()">' + divToPrint.innerHTML + '</body></html>');
            newWin.document.close();
            setTimeout(function () {
                newWin.close();
            }, 10);
        }
    </script>
</body>
</html>