SysReservacionEventosESFE.UI.AppWebAspNetCore/Controllers/CarreraController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

/********************************/
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication.Cookies;
using SysReservacionEventosESFE.EntidadesDeNegocio;
using SysReservacionEventosESFE.LogicaDeNegocio;
using SysReservacionEventosESFE.UI.AppWebAspNetCore.Models;

namespace SysReservacionEventosESFE.UI.AppWebAspNetCore.Controllers
{
    [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme)]
    public class CarreraController : Controller
    {
        CarreraBL carreraBL = new CarreraBL();

        // GET: RolController
        [AuthorizeUser(IdAcceso: 4)]

        public async Task<IActionResult> Index(Carrera pCarrera = null)
        {
            if (pCarrera == null)
                pCarrera = new Carrera();
            if (pCarrera.Top_Aux == 0)
                pCarrera.Top_Aux = 10;
            else if (pCarrera.Top_Aux == -1)
                pCarrera.Top_Aux = 0;
            var carreras = await carreraBL.BuscarAsync(pCarrera);
            ViewBag.Top = pCarrera.Top_Aux;
            return View(carreras);
        }

        // GET: RolController/Details/5
        [AuthorizeUser(IdAcceso: 4)]
        public async Task<IActionResult> Details(int IdCarrera)
        {
            var carrera = await carreraBL.ObtenerPorIdAsync(new Carrera { IdCarrera = IdCarrera });
            return View(carrera);
        }

        // GET: RolController/Create
        [AuthorizeUser(IdAcceso: 4)]
        public IActionResult Create()
        {
            ViewBag.Error = "";
            return View();
        }

        // POST: RolController/Create
        [AuthorizeUser(IdAcceso: 4)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Carrera pCarrera)
        {
            try
            {
                int result = await carreraBL.CrearAsync(pCarrera);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(pCarrera);
            }
        }

        // GET: RolController/Edit/5
        [AuthorizeUser(IdAcceso: 4)]
        public async Task<IActionResult> Edit(Carrera pCarrera)
        {
            var carrera = await carreraBL.ObtenerPorIdAsync(pCarrera);
            ViewBag.Error = "";
            return View(carrera);
        }

        // POST: RolController/Edit/5
        [AuthorizeUser(IdAcceso: 4)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int IdCarrera, Carrera pCarrera)
        {
            try
            {
                int result = await carreraBL.ModificarAsync(pCarrera);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(pCarrera);
            }
        }

        // GET: RolController/Delete/5
        [AuthorizeUser(IdAcceso: 4)]
        public async Task<IActionResult> Delete(Carrera pCarrera)
        {
            ViewBag.Error = "";
            var carrera = await carreraBL.ObtenerPorIdAsync(pCarrera);
            return View(carrera);
        }

        // POST: RolController/Delete/5
        [AuthorizeUser(IdAcceso: 4)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int IdCarrera, Carrera pCarrera)
        {
            try
            {
                int result = await carreraBL.EliminarAsync(pCarrera);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(pCarrera);
            }
        }
    }
}

SysReservacionEventosESFE.UI.AppWebAspNetCore/Views/Carrera/Create.cshtml
@model SysReservacionEventosESFE.EntidadesDeNegocio.Carrera
@{
    Layout = null;
}
@{
    ViewData["Title"] = "Create";
}

<h1>Agregar carrera</h1>
<hr />


<form asp-action="Create">

    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
        </div>
    </div>
    @*BOTONES GUARDAR Y CANCELAR*@

    <div class="form-group" style="margin-top: 10px;">
        <button type="submit" class="btn btn-success" style="margin-right: 10px;">
            <i class="fas fa-save"></i> Guardar
        </button>

        <button type="button" class="btn btn-danger" onclick="window.location.href='@Url.Action("Index")'" style="margin-left: 10px;">
            <i class="fas fa-times"></i> Cancelar
        </button>
    </div>

    <span class="text-danger">@ViewBag.Error</span>

</form>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

SysReservacionEventosESFE.UI.AppWebAspNetCore/Views/Carrera/Delete.cshtml
@model SysReservacionEventosESFE.EntidadesDeNegocio.Carrera

@{
    ViewData["Title"] = "Delete";
}
<h1>Eliminar carrera</h1>

<h3>¿ Esta seguro que desea eliminar ?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
    </dl>

    @* FUNCTION ELIMINAR ROL*@
    @using (Html.BeginForm("Delete", "Carrera", new { IdCarrera = Model.IdCarrera }, FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <button type="submit" class="btn btn-danger" onclick="return confirm('¿Está seguro de eliminar?');" style="margin-left: 10px;">
            <i class="fas fa-trash"></i> Eliminar
        </button>

        <button type="button" class="btn btn-secondary" onclick="window.location.href='@Url.Action("Index")'" style="margin-left: 10px;">
            <i class="fas fa-times"></i> Cancelar
        </button>
        <span class="text-danger">@ViewBag.Error</span>
    }

</div>

SysReservacionEventosESFE.UI.AppWebAspNetCore/Views/Carrera/Details.cshtml
@model SysReservacionEventosESFE.EntidadesDeNegocio.Carrera

@{
    ViewData["Title"] = "Details";
}

<h1>Detalles de carrera</h1>
<hr />
<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
    </dl>
</div>

@*BOTONES DE DETALLES DE ROL*@

<td class="botonestabla">
    <button type="button" class="btn btn-success" style="background-color: #264DA0; color: white; margin-right: 10px;" onclick="window.location.href='@Url.Action("Edit", new { IdCarrera = Model.IdCarrera })'">
        <i class="fas fa-pencil-alt"></i> Ir a Modificar
    </button>
</td>

<td class="botonestabla">
    <button type="button" class="btn btn-danger" onclick="window.location.href='@Url.Action("Index")'" style="margin-left: 10px;">
        <i class="fas fa-times"></i> Cancelar
    </button>
</td>

SysReservacionEventosESFE.UI.AppWebAspNetCore/Views/Carrera/Edit.cshtml
@model SysReservacionEventosESFE.EntidadesDeNegocio.Carrera

@{
    ViewData["Title"] = "Edit";
}
<h1>Modificar carrera</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdCarrera" class="form-control" />
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>

            @*BOTONES DE EDIT DE ROL*@

            <div class="form-group" style="margin-top: 10px;">
                <button type="submit" class="btn btn-success" style="margin-right: 10px;">
                    <i class="fas fa-save"></i> Guardar
                </button>

                <button type="button" class="btn btn-danger" onclick="window.location.href='@Url.Action("Index")'" style="margin-left: 10px;">
                    <i class="fas fa-times"></i> Cancelar
                </button>
            </div>
            <span class="text-danger">@ViewBag.Error</span>

        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script>
        $(function () {
            $("form input[name]").trigger("blur");
        });
    </script>
} 

SysReservacionEventosESFE.UI.AppWebAspNetCore/Views/Carrera/Index.cshtml
@model IEnumerable<SysReservacionEventosESFE.EntidadesDeNegocio.Carrera>


@{
    ViewData["Title"] = "Index";
    int numPage = 1;
    int numRegistros = 0;
    int numRegistrosPorPage = 10;
    int[] tops = { 10, 20, 50, 100, 500, 1000, 10000, -1 };
    int topActual = Convert.ToInt32(ViewBag.Top);
}
<h1>Buscar carrera</h1>
<div class="row">
    <div class="col-md-12">
        <form asp-action="Index">
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label class="control-label">Nombre</label>
                        <input type="text" class="form-control" name="nombre" />
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        <label class="control-label">Top</label>
                        <select name="top_aux" class="form-control">
                            @foreach (var item in tops)
                            {
                                string strItem = item != -1 ? item.ToString() : "Todos";
                                if (item != topActual)
                                {
                                    <option value="@item">@strItem</option>
                                }
                                else
                                {
                                    <option selected value="@item">@strItem</option>
                                }
                            }
                        </select>
                    </div>
                </div>
            </div>

            @*BOTONES DE CREAR Y BUSCAR DE ROL*@


            <div class="form-group" style="margin-top: 10px;">
                <button type="submit" class="btn btn-primary" style="background-color: #0074D9; color: white;">
                    <i class="fas fa-search"></i> Buscar
                </button>


                <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="">
                    <i class="fas fa-plus"></i> Agregar
                </button>
            </div>

            <span class="text-danger">@ViewBag.Error</span>

        </form>
    </div>
</div>



<table class="table table-responsive paginationjs">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th colspan="3">Acciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr data-page="@numPage">
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>

                @*BOTONES CRUD EDITAR - LEER - ELIMINAR ROL*@



                <td class="botonestabla">
                    <button type="button" class="btn btn-primary" style="background-color: #264DA0; color: white" onclick="window.location.href='@Url.Action("Edit", new { IdCarrera = item.IdCarrera })'">
                        <i class="fas fa-pencil-alt"></i> Modificar
                    </button>
                </td>


                <td class="botonestabla">
                    <button type="button" class="btn btn-info" onclick="window.location.href='@Url.Action("Details", new { IdCarrera = item.IdCarrera })'">
                        <i class="fas fa-eye"></i> Detalles
                    </button>
                </td>
                <td class="botonestabla">
                    <button type="button" class="btn btn-danger" onclick="window.location.href='@Url.Action("Delete", new { IdCarrera = item.IdCarrera })'">
                        <i class="fas fa-trash"></i> Eliminar
                    </button>
                </td>

            </tr>
            numRegistros++;
            if (numRegistros == numRegistrosPorPage)
            {
                numPage++;
                numRegistros = 0;
            }
        }
        @{
            if (numRegistros == 0)
            {
                numPage--;
            }
        }
    </tbody>
</table>
@if (numPage > 1)
{
    <div class="row" style="overflow:auto">
        <div class="col-md-12">
            <ul class="pagination paginationjs" data-numpage="@numPage" data-pageactive="1">
                <li class="page-item" data-typepage="Previous"><a class="page-link" href="#">Previous</a></li>
                @for (var i = 1; i <= numPage; i++)
                {
                    <li class="page-item" data-page="@i" data-typepage="Item"><a class="page-link" href="#">@i</a></li>
                }
                <li class="page-item" data-typepage="Next"><a class="page-link" href="#">Next</a></li>
            </ul>
        </div>
    </div>
}


<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <!-- Puedes cambiar 'modal-lg' por 'modal-sm' o personalizar el tamaño según tus necesidades -->
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">
                    Título del Modal
                </h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                </button>
            </div>
            <div class="modal-body">
                <!-- Contenido del cuerpo del modal -->
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-dark" data-bs-dismiss="modal"> Cerrar </button>

            </div>
        </div>
    </div>
</div>
<script>
    var exampleModal = document.getElementById('exampleModal');
    exampleModal.addEventListener('show.bs.modal', function (event) {
        var button = event.relatedTarget;
        var recipient = button.getAttribute('data-bs-whatever');

        $.get('/Carrera/Create', function (data) {
            var modalTitle = exampleModal.querySelector('.modal-title');
            modalTitle.textContent = 'Carrera' + recipient;

            var modalBody = exampleModal.querySelector('.modal-body');
            modalBody.innerHTML = data;
        });
    });
</script>